[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
ffi = true
verbosity = 5

# Add this section (critical for imports)
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@arachnid/=lib/solidity-stringutils/src/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config